@startsalt

<style>
saltDiagram {
  BackgroundColor #EEEBDC
}
</style>

title PÁGINA INICIAL
'header index.html
'footer Projeto Integrador Univesp

{+
  .
  = <&chevron-left> CONTROLE DA DENGUE <&chevron-right>
  .
  ..
  ==== <U+2800> Página criada com a finalidade
  ==== <U+2800> de registro e consulta de casos
  ==== <U+2800> de Dengue na população.
  ..
  .
  .
  === <U+2800> Escolha o que deseja fazer:
  .
  [=== Registrar uma Ocorrência ]
  .
  [===   Visualizar Ocorrências ]
  .
  .
}
@endsalt