@startsalt

<style>
saltDiagram {
  BackgroundColor #EEEBDC
}
</style>

title OCORRÊNCIAS - BAIRROS

{+
  .
  = <&chevron-left> VISUALIZAR OCORRÊNCIAS <&chevron-right>
  = <&account-login> BAIRROS
  .
  ..
  .
  {
    <U+2800>|
    ^Selecione um Estado          ^
    .
    <U+2800>|
    ^Selecione uma Cidade         ^
  }
  .
  ..
  == <U+2800> Total na Cidade: XXXXX
  ..
  .
  === <U+2800> Resumo por Bairro:
  {
    <U+2800>|
    {#
      <U+2800><U+2800><U+2800><U+2800><U+2800><U+2800><U+2800>Bairro<U+2800><U+2800><U+2800><U+2800><U+2800><U+2800>|<U+2800><U+2800><U+2800>Casos<U+2800><U+2800><U+2800>
      <U+2800>Bairro 01...|<U+2800><U+2800><U+2800><U+0020>XXXX
      <U+2800>Bairro 02...|<U+2800><U+2800><U+2800><U+0020>XXXX
      <U+2800>Bairro 03...|<U+2800><U+2800><U+2800><U+0020>XXXX
      <U+2800>Bairro 04...|<U+2800><U+2800><U+2800><U+0020>XXXX
      <U+2800>........|<U+2800><U+2800>.... 
    }
  }
  .
  .
}
@endsalt