@startsalt

<style>
saltDiagram {
  BackgroundColor #EEEBDC
}
</style>

title REGISTRAR OCORRÊNCIA

{+
  .
  = <&chevron-left> REGISTRE SUA OCORRÊNCIA <&chevron-right>
  .
  ..
  ==== <U+2800> Página criada com a finalidade
  ==== <U+2800> de registro de ocorrências de Dengue.
  ..
  .
  .
  === <U+2800> Insira os dados da ocorrência:
  .
  {
    <U+2800> CPF: | "000.000.000-00"
    .
    <U+2800> Cep: | "00.000-000    " | [Buscar Cep]
    .
    <U+2800> Número: | "0000          "
    .
    <U+2800> Data Nasc: | "00/00/0000    "
    .
    <U+2800> Ocorrência: | "00/00/0000    "

    .
  }
  .
  [===   Enviar Ocorrência             ]
  .
  [===   CANCELAR                      ]
  .
}
@endsalt