@startsalt

<style>
saltDiagram {
  BackgroundColor #EEEBDC
}
</style>

title OCORRÊNCIAS - CIDADES

{+
  .
  = <&chevron-left> VISUALIZAR OCORRÊNCIAS <&chevron-right>
  = <&account-login> CIDADES
  .
  ..
  .
  {
    <U+2800>|
    ^Selecione um Estado          ^
  }
  .
  ..
  == <U+2800> Total no Estado: XXXXX
  ..
  .
  === <U+2800> Resumo por Cidade:
  {
    <U+2800>|
    {#
      <U+2800><U+2800><U+2800>Cidade<U+2800><U+2800><U+2800>|<U+2800>Cód. IBGE<U+2800>|<U+2800><U+2800>Casos<U+2800><U+2800>
      <U+2800>Adamantina|<U+0020>350010505|<U+2800><U+2800><U+0020>XXXX     
      <U+2800>XXXX|<U+2800><U+2800>XXXXX|<U+2800><U+2800><U+0020>XXXX  
      <U+2800>XXXX|<U+2800><U+2800>XXXXX|<U+2800><U+2800><U+0020>XXXX  
      <U+2800>XXXX|<U+2800><U+2800>XXXXX|<U+2800><U+2800><U+0020>XXXX  
      <U+2800>XXXX|<U+2800><U+2800>XXXXX|<U+2800><U+2800><U+0020>XXXX
      <U+2800>........|<U+2800>....|<U+2800><U+2800>.... 
    }
  }
  .
  .
}
@endsalt